% script to test out parameter recovery with uHGF in new toolbox


toolboxroot = '..\..\..\hgf-toolbox';
run(fullfile(toolboxroot, 'setup.m'));
addpath('..');


% get input
run1 = importdata('sub-01_facehouse-MRI_run1_15-01-24_11-23-08.mat');
run2 = importdata('sub-01_facehouse-MRI_run2_15-01-24_11-35-43.mat');
u = [run1.cue == run1.outcome; run2.cue == run2.outcome];

% load configs
[prc_config, obs_config] = cbbu_uHGF_AR1_3level_config;
optim_config = quasinewton_optim_config;
optim_config.nRandInit = 4;


% Sim
r.c_prc = prc_config;
prc_params = uhgf_ar1_binary_transp(r, prc_config.priormus);

prc_params2 = [NaN 0 1 NaN 1 1 NaN 0 0.3 NaN 0 1 NaN 0 0 1 1 NaN -2.5 3];



sim = simModel(u,...
                     'uhgf_ar1_binary',...
                     prc_params,...
                     'unitsq_sgm',...
                     5,...
                     123456789);

est = fitModel(...
                    sim.y,...
                    sim.u,...
                    prc_config,...
                    obs_config,...
                    optim_config);


%%
% 
% % run recovery
% N=100;
% 
% % Parameters to recover
% prc_param_names = {'phi', 'om2', 'om3'};
% prc_param_idx   = [9, 16, 17];
% prc_param_space = {'native', 'native'};
% obs_param_names = {'zeta'};
% obs_param_idx   = 1;
% obs_param_space = {'log'};
% 
% recov = cbbu_parameter_recovery_master_parallel( ...
%     u,...
%     prc_config,...
%     obs_config,...
%     optim_config,...
%     N,...
%     8, ...
%     prc_param_names,...
%     prc_param_idx,...
%     prc_param_space,...
%     obs_param_names,...
%     obs_param_idx,...
%     obs_param_space);
% 
% 
% save('cbbu_uHGF_3level_recov.mat', 'recov');
% recovery_figures(recov);

